// Quiz content. One best answer per MCQ; `answer` is the index into `options`.
// Every answer matches the page and the verified research notes. `refs` are ref ids rendered with cite().

export const TOPICS = [
  { value: 'all', label: 'All' },
  { value: 'anatomy', label: 'Anatomy' },
  { value: 'technique', label: 'Technique' },
  { value: 'drugs', label: 'Drugs' },
  { value: 'ultrasound', label: 'Ultrasound' },
  { value: 'troubleshooting', label: 'Troubleshooting' },
  { value: 'anticoagulation', label: 'Anticoagulation' },
  { value: 'complications', label: 'Complications' },
];

export const MCQS = [
  {
    topic: 'anatomy',
    tier: 2,
    stem: 'In adults, where does the conus medullaris most often end?',
    options: ['T10–T11', 'L1–L2', 'L3–L4', 'S1–S2'],
    answer: 1,
    explain: 'In an MRI study of 504 adults the mean position was the lower third of L1, with a range from the middle of T12 to the upper third of L3. That range is why spinals go in at L3–4 or below. The dural sac, not the cord, ends around S2.',
    refs: [],
    link: '#an-conus',
  },
  {
    topic: 'anatomy',
    tier: 2,
    stem: 'Which structure does a paramedian approach avoid that a midline approach passes through?',
    options: ['Ligamentum flavum', 'Dura mater', 'Interspinous ligament', 'Arachnoid mater'],
    answer: 2,
    explain: 'The paramedian needle enters beside the spinous processes and passes through paraspinal muscle to the ligamentum flavum, so it skips the supraspinous and interspinous ligaments. Useful when these are calcified or flexion is poor.',
    refs: [],
    link: '#an-layers',
  },
  {
    topic: 'anatomy',
    tier: 2,
    stem: 'In an MRI study, how often did anaesthetists correctly identify a marked lumbar interspace by palpation?',
    options: ['About 29%', 'About 50%', 'About 75%', 'About 95%'],
    answer: 0,
    explain: 'Only 29% were correct, and the space was usually higher than the anaesthetist believed. Combined with a low conus, this is why you aim for L3–4 or below and treat Tuffier’s line as a rough guide.',
    refs: [],
    link: '#an-tuffier',
  },
  {
    topic: 'technique',
    tier: 1,
    stem: 'Which single change most reduces the risk of post-dural puncture headache?',
    options: ['Bed rest for 24 h after the spinal', 'Inserting the cutting bevel perpendicular to the spine', 'Generous IV fluids after the spinal', 'A pencil-point rather than a cutting needle'],
    answer: 3,
    explain: 'Atraumatic (pencil-point) needles cut the incidence from 11.0% to 4.2% in a meta-analysis of 31,412 patients. Bed rest and fluids do not prevent PDPH. With cutting needles, a bevel parallel (not perpendicular) to the long axis is the lower-risk orientation.',
    refs: ['uppal2023'],
    link: '#cx-pdph',
  },
  {
    topic: 'technique',
    tier: 1,
    stem: 'Which skin preparation practice best protects the CSF from chlorhexidine?',
    options: ['Apply it, let it dry fully, and keep it away from the drugs and needles', 'Pour chlorhexidine into a pot on the sterile trolley for easy re-use', 'Wipe it off with saline before puncture', 'Use 2% rather than 0.5% so less volume is needed'],
    answer: 0,
    explain: 'Chlorhexidine is neurotoxic. Keep it well away from the neuraxial drugs and equipment, never in pots on or near the same surface, and let it dry before you touch or puncture the skin. The Association of Anaesthetists prefers 0.5% chlorhexidine in alcohol.',
    refs: ['tq-campbell2014'],
    link: '#cx-wrong-route',
  },
  {
    topic: 'drugs',
    tier: 2,
    stem: 'Transient neurological symptoms after spinal anaesthesia are most strongly associated with which drug?',
    options: ['Bupivacaine', 'Prilocaine', 'Levobupivacaine', 'Lidocaine'],
    answer: 3,
    explain: 'In 1,863 patients, lidocaine carried a relative risk of 5.1 compared with bupivacaine. Lithotomy and day-case status increased the risk further.',
    refs: [],
    link: '#cx-tns',
  },
  {
    topic: 'drugs',
    tier: 2,
    stem: 'For a hyperbaric spinal, which factors matter most for how far the block spreads?',
    options: ['Patient weight and sex', 'Needle gauge and bevel direction', 'Baricity of the solution and the patient’s position', 'Speed of injection and barbotage'],
    answer: 2,
    explain: 'Baricity and position during and just after injection, with the dose, are the main controllable factors. Lumbosacral CSF volume explains much of the remaining variation but can’t be measured at the bedside. Speed of injection and barbotage have small, inconsistent effects.',
    refs: [],
    link: '#tq-spread-h',
  },
  {
    topic: 'drugs',
    tier: 2,
    stem: 'According to the bupivacaine product label, what is the maximum dose in any 4-hour period?',
    options: ['1 mg/kg', '2 mg/kg', '3 mg/kg', '5 mg/kg'],
    answer: 1,
    explain: 'No more than 2 mg/kg in any 4 hours, with single doses up to 150 mg. A spinal dose is a small fraction of this, but add it to any peripheral block or infiltration given to the same patient.',
    refs: ['cx-marcain-smpc'],
    link: '#cx-last',
  },
  {
    topic: 'ultrasound',
    tier: 2,
    stem: 'Scanning in the paramedian sagittal oblique view, you find the flat bright sacrum. What is the first gap cranial to it?',
    options: ['L3–4', 'L4–5', 'L5–S1', 'S1–S2'],
    answer: 2,
    explain: 'The sacrum is a continuous bright line with no gaps. The first gap above it is L5–S1, the largest interlaminar space. Count up from there.',
    refs: [],
    link: '#us-mark-level',
  },
  {
    topic: 'ultrasound',
    tier: 2,
    stem: 'Most of the evidence for ultrasound in neuraxial anaesthesia supports which use?',
    options: ['Real-time in-plane needle guidance', 'A pre-procedure scan to mark the level, midline and depth', 'Confirming CSF flow after puncture', 'Measuring block height after injection'],
    answer: 1,
    explain: 'The trials and meta-analyses mostly studied a pre-procedure scan: mark the skin, wipe off the gel and insert the needle as usual. Real-time guidance is technically demanding with limited data.',
    refs: [],
    link: '#us-marking',
  },
  {
    topic: 'troubleshooting',
    tier: 1,
    stem: 'During injection the patient reports sharp pain shooting down one leg. What should you do?',
    options: ['Stop injecting, withdraw and redirect or re-site', 'Inject faster to finish quickly', 'Continue, as this is normal with hyperbaric solutions', 'Give IV fentanyl and continue'],
    answer: 0,
    explain: 'Pain on injection or persistent paraesthesia: stop, don’t inject, withdraw and redirect. Two-thirds of neurological deficits in a large French survey followed paraesthesia during puncture or pain on injection.',
    refs: [],
    link: '#ts-paraesthesia',
  },
  {
    topic: 'troubleshooting',
    tier: 2,
    stem: 'When is a repeat spinal most reasonable after a failed first attempt?',
    options: ['When there is no appreciable block at all after 15–20 min, and the cause has been dealt with', 'When the first block is patchy but rising slowly at 10 min', 'Whenever the surgeon is in a hurry', 'Always, using the same full dose'],
    answer: 0,
    explain: 'Repeat only after a complete failure, judged at 15–20 min. Repeating onto a slow or partial block risks an unpredictable high spinal and neurotoxic concentrations of local anaesthetic.',
    refs: [],
    link: '#ts-failed',
  },
  {
    topic: 'troubleshooting',
    tier: 1,
    stem: 'A patient with a high spinal is hypotensive and bradycardic. Which position is recommended?',
    options: ['Head-down tilt', 'Sitting upright', 'Prone', 'Supine with the legs elevated, no head-down tilt'],
    answer: 3,
    explain: 'Elevate the legs to help venous return without tipping the head down, which could carry hyperbaric drug higher. Support the airway and circulation and call for help.',
    refs: ['ts-qrh2023'],
    link: '#ts-high-spinal',
  },
  {
    topic: 'anticoagulation',
    tier: 2,
    stem: 'A patient takes apixaban 5 mg twice daily for atrial fibrillation. What is the minimum interval from the last dose to a spinal?',
    options: ['12 h', '24 h', '36 h', '72 h'],
    answer: 3,
    explain: 'This is a high dose (AF stroke prevention). Both ESAIC/ESRA 2022 and ASRA 2025 give 72 h. 36 h applies only to low-dose prophylaxis after hip or knee replacement; ASRA counts the dose-reduced AF dose (also 2.5 mg twice daily) as high dose.',
    refs: ['esaic2022', 'asra2025'],
    link: '#tq-ac-full',
  },
  {
    topic: 'anticoagulation',
    tier: 2,
    stem: 'A patient had enoxaparin 40 mg once daily for thromboprophylaxis. How long after the last dose can a spinal be done, with normal renal function?',
    options: ['4 h', '12 h', '24 h', '72 h'],
    answer: 1,
    explain: 'Low-dose LMWH: at least 12 h. High (treatment) doses need 24 h, and ESAIC/ESRA extend the low-dose interval to 24 h if creatinine clearance is under 30 mL/min.',
    refs: ['esaic2022', 'asra2025'],
    link: '#tq-ac-full',
  },
  {
    topic: 'complications',
    tier: 2,
    stem: 'Under ICHD-3, which feature is required to diagnose post-dural puncture headache?',
    options: ['The headache is relieved within 15 min of lying flat', 'The headache starts within 5 days of a dural puncture', 'There is tinnitus or hearing loss', 'A blood patch relieves it'],
    answer: 1,
    explain: 'ICHD-3 requires a dural puncture and onset within 5 days, not better explained by another diagnosis. The postural feature is typical but no longer a required criterion.',
    refs: ['cx-ichd3', 'uppal2023'],
    link: '#cx-pdph',
  },
  {
    topic: 'complications',
    tier: 3,
    stem: 'What volume of blood does the 2023 multisociety consensus most often recommend for an epidural blood patch?',
    options: ['15–20 mL', '5 mL', '40 mL', 'As much as possible, up to 60 mL'],
    answer: 0,
    explain: 'Usually 15–20 mL, injected slowly, stopping if back pain, headache or radicular pressure becomes significant. More than 30 mL did not improve success.',
    refs: ['uppal2023'],
    link: '#cx-pdph',
  },
  {
    topic: 'complications',
    tier: 1,
    stem: 'Eight hours after a spinal the block had been wearing off, but now the patient’s legs are weaker and they have new back pain. What next?',
    options: ['Reassure: this is transient neurological symptoms', 'Wait a further 6 h for the block to wear off', 'Urgent MRI, call a senior anaesthetist and refer to neurosurgery', 'Give naloxone'],
    answer: 2,
    explain: 'A block that returns or worsens, with new back pain, is a vertebral canal haematoma or abscess until proven otherwise. ESAIC/ESRA advise urgent MRI and decompression, if indicated, within 6 h. TNS causes pain without weakness.',
    refs: ['esaic2022'],
    link: '#cx-haematoma',
  },
  {
    topic: 'complications',
    tier: 1,
    stem: 'How do NRFit (ISO 80369-6) connectors prevent wrong-route injection?',
    options: ['They are colour-coded yellow only', 'They contain a one-way valve', 'They will not connect to Luer syringes or lines', 'They only fit 25G needles'],
    answer: 2,
    explain: 'NRFit is a neuraxial-specific connector that will not mate with Luer, so an IV syringe or line can’t be attached to a spinal needle or epidural, and vice versa.',
    refs: ['iso80369-6'],
    link: '#cx-wrong-route',
  },
  {
    topic: 'complications',
    tier: 2,
    stem: 'Local anaesthetic systemic toxicity: what is the initial bolus of 20% lipid emulsion on the Association of Anaesthetists card?',
    options: ['0.5 mL/kg over 10 min', '5 mL/kg over 1 min', '100 mL regardless of weight', '1.5 mL/kg over 2–3 min'],
    answer: 3,
    explain: '1.5 mL/kg over 2–3 min, then an infusion of 15 mL/kg/h. Repeat the bolus at 5 and 10 min and double the infusion to 30 mL/kg/h if needed, to a maximum cumulative 12 mL/kg. Propofol is not a substitute.',
    refs: ['cx-qrh310'],
    link: '#cx-last',
  },
  {
    topic: 'technique',
    tier: 1,
    stem: 'An 84-year-old with a painful hip fracture is booked for a spinal. What is the sensible first step before you position her?',
    options: ['Sit her upright to open the interspace', 'Give a femoral or fascia iliaca block (with supervision)', 'Give a large fluid bolus to prevent hypotension', 'Skip the checks to shorten the time she is in pain'],
    answer: 1,
    explain: 'An analgesic block before positioning makes the move kinder and often lets the patient stay still. Check anticoagulant timing, platelets, haemoglobin and electrolytes first, and correct hypovolaemia gently. Large fluid boluses can harm a weak heart; small, slow boluses and an early vasopressor are safer.',
    refs: ['pp-griffiths2021'],
    link: '#tq-hipfracture',
  },
  {
    topic: 'complications',
    tier: 1,
    stem: 'A patient’s leg block had worn off, but six hours later the legs are numb and weak again. What should the ward do?',
    options: ['Wait for the morning round', 'Give more analgesia and reassure', 'Call the anaesthetist urgently', 'Ask the patient to walk to test the legs'],
    answer: 2,
    explain: 'Leg weakness or numbness that returns after it had worn off is a red flag. Call the anaesthetist at once and do not wait for the morning round. A senior should be told straight away.',
    refs: ['esaic2022'],
    link: '#tq-postop',
  },
  {
    topic: 'technique',
    tier: 1,
    stem: 'Which record should always be made straight after a spinal?',
    options: ['Only the name of the drug', 'The number of attempts, any paraesthesia or blood, the drug and dose, the block height and the ward instructions', 'Nothing, if the block went well', 'Only the surgeon’s name and the theatre'],
    answer: 1,
    explain: 'The record should let the next anaesthetist, the surgeon and the ward understand exactly what was done: consent, time and position, asepsis, level, needle and attempts, CSF, drug (with batch number), block height, observations, complications and ward instructions with red flags.',
    refs: [],
    link: '#tq-documentation',
  },
  {
    topic: 'technique',
    tier: 2,
    stem: 'Why do you write “no paraesthesia, CSF clear” in the notes even when nothing went wrong?',
    options: ['It is a legal formality with no clinical value', 'It lets you skip the block height check', 'Without it, a later reader cannot tell whether it did not happen or was not noted', 'It reduces the risk of post-dural puncture headache'],
    answer: 2,
    explain: 'Negative findings make the record complete. If the record is silent, a later reader cannot tell whether a problem was absent or simply not written down, which matters if a deficit appears.',
    refs: [],
    link: '#tq-documentation',
  },
  {
    topic: 'drugs',
    tier: 1,
    stem: 'You are preparing a spinal for a frail 85-year-old. Which plan fits best?',
    options: ['Same dose as a young adult, vasopressor only if needed', 'Dose at the cautious end of the label range, vasopressor drawn up first, and blood pressure checked often', 'Large fluid bolus and no vasopressor', 'Avoid monitoring to keep the patient calm'],
    answer: 1,
    explain: 'Older patients are more prone to hypotension, and spread may be a little higher. Use the lowest dose that works from the label range, draw up a vasopressor before you inject, and check blood pressure at short intervals until the level has fixed.',
    refs: ['pp-griffiths2021'],
    link: '#pp-older',
  },
  {
    topic: 'ultrasound',
    tier: 2,
    stem: 'In a trial of patients with difficult landmarks (high BMI, moderate to severe scoliosis or previous lumbar surgery), what did a pre-procedure scan change?',
    options: ['More first-attempt successes and fewer insertion attempts', 'It removed the need for any skin marking', 'It replaced the need for CSF to be seen', 'It made no difference to the number of attempts'],
    answer: 0,
    explain: 'In the trial summarised on the page, spinal success on the first attempt was 65% with a scan versus 32% with landmarks, and the median number of insertions was 1 versus 2. A pre-procedure scan helps most in obesity, scoliosis and previous spine surgery.',
    refs: [],
    link: '#ultrasound',
  },
  {
    topic: 'technique',
    tier: 2,
    stem: 'Which description of a saddle block is correct?',
    options: ['The patient lies flat at once so the block rises to T10', 'The patient sits for the injection and stays sitting for a few minutes so a hyperbaric drug settles in the lowest part of the dural sac', 'A large volume of plain solution is injected quickly', 'The patient is placed head-down immediately after injection'],
    answer: 1,
    explain: 'A saddle block aims at the sacral roots only (perineum, anus, inner thighs). Use L3–4 or below, a small dose of hyperbaric drug injected slowly, then lie the patient back carefully and check the level at once and again as it settles.',
    refs: [],
    link: '#tq-saddle',
  },
  {
    topic: 'technique',
    tier: 3,
    stem: 'You plan a unilateral spinal with a pencil-point needle. Which step makes a one-sided block more likely?',
    options: ['Turn the side opening towards the dependent (operative) side before injecting, inject slowly and keep the patient on that side', 'Inject quickly with the opening facing the non-operative side', 'Lie the patient flat immediately after injection', 'Use plain bupivacaine, which is slightly hypobaric at body temperature, for the most predictable result'],
    answer: 0,
    explain: 'Hyperbaric drug settles on the dependent side, and the jet goes first towards the side the opening faces. The longer the patient stays on that side, the more one-sided the block. A block that has become bilateral is common and is not a failure, but you must test both sides and know about it.',
    refs: [],
    link: '#tq-saddle',
  },
  {
    topic: 'complications',
    tier: 3,
    stem: 'A frail patient is having a cemented hemiarthroplasty under spinal. Which statement is correct?',
    options: ['Spinal anaesthesia prevents bone cement implantation syndrome', 'Nothing can be done in advance, so just wait and see', 'Tell the surgeon your concern before the cement goes in, raise the inspired oxygen, have a vasopressor ready and treat early', 'It only happens under general anaesthesia'],
    answer: 2,
    explain: 'Cementing and prosthesis insertion can cause a sudden fall in blood pressure, hypoxia or arrhythmia. Frailty and heart or lung disease raise the risk, and a spinal does not prevent it.',
    refs: [],
    link: '#tq-hipfracture',
  },
  {
    topic: 'anatomy',
    tier: 3,
    stem: 'A patient has an exaggerated thoracic kyphosis. What is the consequence for a hyperbaric spinal?',
    options: ['The textbook pooling point may not apply, so the block may be higher or lower than expected', 'Hyperbaric solution cannot be used', 'The block will always be exactly at T5–6', 'Baricity no longer matters'],
    answer: 0,
    explain: 'The textbook pooling point (the trough of the thoracic kyphosis, around T5–6) assumes a typical spine. An exaggerated kyphosis or a scoliosis moves the lowest point of the curve. Watch the level rise before the surgeon starts, and be wary of how table tilt interacts with the curves.',
    refs: [],
    link: '#anatomy',
  },
];

// SAQ / viva questions with model-answer points and marks.
export const SAQS = [
  {
    id: 'qz-saq-anatomy',
    tier: 2,
    q: 'Describe the structures a midline spinal needle passes through at L3–4, and explain why the level matters.',
    marks: 10,
    points: [
      ['Skin, subcutaneous fat, supraspinous ligament, interspinous ligament, ligamentum flavum, epidural space, dura and arachnoid, subarachnoid space (in order)', 3],
      ['Paramedian approach skips the supraspinous and interspinous ligaments', 1],
      ['Conus ends at a mean of the lower third of L1, range T12 to L3', 2],
      ['Palpation identifies the space correctly only about 29% of the time, usually one or more levels higher than believed; Tuffier’s line is unreliable', 2],
      ['Conus injury has followed spinals placed higher than intended: insert at L3–4 or below, and consider ultrasound to confirm level', 2],
    ],
  },
  {
    id: 'qz-saq-spread',
    tier: 2,
    q: 'What factors affect the spread of intrathecal local anaesthetic? Which are most important?',
    marks: 10,
    points: [
      ['Drug: baricity (most important with position), dose (mass), volume at fixed concentration, temperature (plain bupivacaine is slightly hypobaric at 37 °C)', 3],
      ['Patient: lumbosacral CSF volume (largest source of variation, not measurable clinically), age, raised intra-abdominal pressure, spinal curvature', 3],
      ['Procedure: position during and after injection, level of injection, speed of injection and barbotage (small, inconsistent effects)', 2],
      ['Most predictable: a small volume of hyperbaric solution injected slowly, with the patient positioned deliberately afterwards', 2],
    ],
  },
  {
    id: 'qz-saq-failed',
    tier: 2,
    q: 'Twenty minutes after a spinal the patient can feel the surgeon’s pinch. Classify the causes of a failed spinal and outline your management.',
    marks: 10,
    points: [
      ['Define: anything from no block to inadequate height, density, duration or side', 1],
      ['Causes (Fettes): failed lumbar puncture; pseudo-success; faulty injection; inadequate spread; failure of drug action; mismanagement of a successful block', 3],
      ['Assess properly: autonomic and motor signs, test from the lowest dermatomes up with cold, pinprick and touch; allow 15–20 min before calling it failed', 2],
      ['Manage by pattern: posture for a low hyperbaric block, unblocked side down if unilateral, supplementation or sedation, GA', 2],
      ['Repeat spinal only after complete failure: risk of high spinal and neurotoxicity; tell the surgeon and patient, document', 2],
    ],
  },
  {
    id: 'qz-saq-pdph',
    tier: 2,
    q: 'A 35-year-old has a headache the day after a spinal for knee arthroscopy. How do you assess and manage it?',
    marks: 10,
    points: [
      ['ICHD-3: onset within 5 days of dural puncture; postural feature typical but not required; neck stiffness, hearing symptoms. Risk factors: younger age, female sex, previous PDPH, cutting or larger needles', 2, ['cx-ichd3', 'uppal2023']],
      ['Red flags and differentials: focal signs, seizures, fever, non-postural or changing headache; meningitis, subdural haematoma, venous sinus thrombosis', 2, ['uppal2023']],
      ['Conservative: paracetamol and NSAID; caffeine up to 900 mg/day in the first 24 h; drink normally; bed rest only for comfort', 2, ['uppal2023']],
      ['Epidural blood patch if activity limited: 15–20 mL at or below the puncture level, stop on back pain or pressure; complete relief 33–91%; counsel about repeat if within 48 h; follow up', 3, ['uppal2023']],
      ['Before a blood patch: exclude fever or sepsis, apply the antithrombotic timing rules, and consent for repeat dural puncture, backache and neurological complications; greater occipital nerve block (after a fine-gauge spinal) is a weaker alternative', 1, ['uppal2023']],
    ],
  },
  {
    id: 'qz-saq-apixaban',
    tier: 2,
    q: 'A patient on apixaban 5 mg twice daily for atrial fibrillation is listed for an elective knee replacement under spinal. How do you plan the anticoagulation?',
    marks: 10,
    points: [
      ['Classify as high dose (AF stroke prevention); check renal function and the time of the last dose', 2],
      ['Stop at least 72 h before the spinal (ESAIC/ESRA 2022; ASRA 2025); 36 h applies only to low-dose prophylaxis after hip or knee replacement; the dose-reduced AF dose of 2.5 mg twice daily still counts as high dose (ASRA 2025)', 3, ['esaic2022', 'asra2025']],
      ['If the interval is uncertain or short: a drug-specific level under 30 ng/mL; reversal agents (PCC, aPCC or andexanet) do not shorten the interval for an elective block', 2, ['esaic2022', 'asra2025']],
      ['Restart: ESAIC/ESRA only after any catheter is removed; ASRA 2025: first high-dose DOAC dose at least 24 h after the puncture; agree with surgeon and physician', 2, ['esaic2022', 'asra2025']],
      ['Document the plan, and do neurological checks after surgery', 1],
    ],
  },
  {
    id: 'qz-saq-high',
    tier: 1,
    q: 'Five minutes after a spinal, the patient says their hands feel weak and it is hard to breathe. Describe your recognition and management.',
    marks: 10,
    points: [
      ['Recognise the sequence (QRH 3-11): hypotension and bradycardia, difficulty breathing, arm weakness, impaired consciousness, then apnoea; it may progress slowly or fast', 2, ['ts-qrh2023']],
      ['Call for help; reassure (the patient may be aware); stop any further local anaesthetic', 1],
      ['Oxygen, jaw thrust, supraglottic airway or intubation with a reduced dose of induction agent; keep the patient asleep once intubated (risk of awareness)', 3, ['ts-qrh2023']],
      ['Circulation: IV fluid, legs elevated without head-down tilt, vasopressors and atropine, early adrenaline if severe; CPR if arrested', 3, ['ts-qrh2023']],
      ['Consider mimics (LAST, vasovagal, haemorrhage, embolism); debrief and document', 1],
    ],
  },
  {
    id: 'qz-saq-haematoma',
    tier: 2,
    q: 'What are the risk factors for, and features of, a vertebral canal haematoma after spinal anaesthesia? How do you manage a suspected case?',
    marks: 10,
    points: [
      ['Rare: e.g. 1 in 200,000 after obstetric epidural vs 1 in 3,600 in women having knee arthroplasty under neuraxial block', 2],
      ['Risk factors: antithrombotic drugs and their combinations, traumatic puncture, catheter insertion and removal, older age, osteoporosis', 2, ['esaic2022']],
      ['Features: new back pain, leg weakness or numbness, bladder or bowel dysfunction, a block that lasts or spreads beyond the drug; motor signs often first', 2, ['esaic2022']],
      ['Urgent MRI, senior anaesthetist, neurosurgery; decompression within 6 h for recovery (ESAIC/ESRA); outcome better within 12 h in a surgical series', 3, ['esaic2022']],
      ['Prevention: follow drug intervals; neuro checks for at least 24 h; document times', 1, ['esaic2022']],
    ],
  },
  {
    id: 'qz-saq-curves',
    tier: 3,
    q: 'A patient with marked kyphoscoliosis is listed for lower-limb surgery under hyperbaric spinal. How do the spinal curves change your plan?',
    marks: 10,
    points: [
      ['Hyperbaric solution pools at the lowest points of the curves, so the textbook pooling point (the trough of the thoracic kyphosis, around T5–6) may not apply', 3],
      ['An exaggerated kyphosis or a scoliosis may give a block higher or lower than expected; table tilt acts through where the curves lie relative to the horizontal', 2],
      ['Give the dose in increments if the technique allows, and watch the level rise before surgery starts', 2],
      ['Expect difficult access: consider a pre-procedure ultrasound scan, a paramedian approach, and a senior’s help', 2],
      ['Be ready for hypotension and a higher-than-planned block; document the level and the plan', 1],
    ],
  },
  {
    id: 'qz-saq-cement',
    tier: 3,
    q: 'A frail 88-year-old has a cemented hemiarthroplasty under spinal. Discuss bone cement implantation syndrome and how you prepare for it.',
    marks: 10,
    points: [
      ['Sudden fall in blood pressure, hypoxia or arrhythmia around cementing and prosthesis insertion', 2],
      ['Risk rises with frailty and heart or lung disease; a spinal does not prevent it', 2],
      ['Tell the surgeon your concern before the cement goes in', 2],
      ['Raise the inspired oxygen, have a vasopressor ready and treat early', 2],
      ['Keep sedation light and blood pressure cycling every minute or two; record the events and the plan for recovery', 2],
    ],
  },
  {
    id: 'qz-saq-restricted',
    tier: 3,
    q: 'How would you try to give a restricted block (saddle or unilateral) with a spinal? What are the limits?',
    marks: 10,
    points: [
      ['Both depend on a hyperbaric solution settling by gravity, so the minutes after injection matter as much as the dose', 2],
      ['Saddle: sit for the injection and stay sitting a few minutes; L3–4 or below; a small dose of hyperbaric drug given slowly', 3],
      ['Unilateral: lie operative side down, inject slowly, keep the patient on that side; orient the side opening of a pencil-point needle towards the dependent side', 3],
      ['Limits: the block may become bilateral or spread further than planned. Test both sides, and agree the drug and dose with your supervisor, using the lowest dose that works', 2],
    ],
  },
  {
    id: 'qz-saq-antiplatelet',
    tier: 3,
    q: 'An 82-year-old with a hip fracture takes aspirin and clopidogrel. How do you decide about a spinal, and what are the competing risks?',
    marks: 10,
    points: [
      ['Many hip fracture patients take an antiplatelet drug. Aspirin alone does not usually delay a spinal; other antiplatelets and any anticoagulant do, so look each drug up', 3, ['asra2025']],
      ['Weigh any delay against the risk of a longer wait for surgery; discuss with the surgeon and a senior', 2, ['pp-griffiths2021']],
      ['If the neuraxial block is not suitable, general anaesthesia is a reasonable alternative; neither is clearly better for every patient', 3],
      ['Whatever you choose, give an analgesic nerve block first, and document the plan and the neurological checks', 2],
    ],
  },
];
