// Quiz content. One best answer per MCQ; `answer` is the index into `options`.
// Every answer matches the page and the verified research notes. `refs` are ref ids rendered with cite().

export const TOPICS = [
  { value: 'all', label: 'All' },
  { value: 'anatomy', label: 'Anatomy' },
  { value: 'technique', label: 'Technique' },
  { value: 'drugs', label: 'Drugs' },
  { value: 'ultrasound', label: 'Ultrasound' },
  { value: 'troubleshooting', label: 'Troubleshooting' },
  { value: 'anticoagulation', label: 'Anticoagulation' },
  { value: 'complications', label: 'Complications' },
];

export const MCQS = [
  {
    topic: 'anatomy',
    stem: 'In adults, where does the conus medullaris most often end?',
    options: ['T10–T11', 'L1–L2', 'L3–L4', 'S1–S2'],
    answer: 1,
    explain: 'In an MRI study of 504 adults the mean position was the lower third of L1, with a range from the middle of T12 to the upper third of L3. That range is why spinals go in at L3–4 or below. The dural sac, not the cord, ends around S2.',
    refs: ['an-saifuddin1998'],
    link: '#an-conus',
  },
  {
    topic: 'anatomy',
    stem: 'Which structure does a paramedian approach avoid that a midline approach passes through?',
    options: ['Ligamentum flavum', 'Dura mater', 'Interspinous ligament', 'Arachnoid mater'],
    answer: 2,
    explain: 'The paramedian needle enters beside the spinous processes and passes through paraspinal muscle to the ligamentum flavum, so it skips the supraspinous and interspinous ligaments. Useful when these are calcified or flexion is poor.',
    refs: [],
    link: '#an-layers',
  },
  {
    topic: 'anatomy',
    stem: 'In an MRI study, how often did anaesthetists correctly identify a marked lumbar interspace by palpation?',
    options: ['About 29%', 'About 50%', 'About 75%', 'About 95%'],
    answer: 0,
    explain: 'Only 29% were correct, and the space was usually higher than the anaesthetist believed. Combined with a low conus, this is why you aim for L3–4 or below and treat Tuffier’s line as a rough guide.',
    refs: ['broadbent2000'],
    link: '#an-tuffier',
  },
  {
    topic: 'technique',
    stem: 'Which single change most reduces the risk of post-dural puncture headache?',
    options: ['Bed rest for 24 h after the spinal', 'Inserting the cutting bevel perpendicular to the spine', 'Generous IV fluids after the spinal', 'A pencil-point rather than a cutting needle'],
    answer: 3,
    explain: 'Atraumatic (pencil-point) needles cut the incidence from 11.0% to 4.2% in a meta-analysis of 31,412 patients. Bed rest and fluids do not prevent PDPH. With cutting needles, a bevel parallel (not perpendicular) to the long axis is the lower-risk orientation.',
    refs: ['tq-nath2018', 'uppal2023'],
    link: '#cx-pdph',
  },
  {
    topic: 'technique',
    stem: 'Which skin preparation practice best protects the CSF from chlorhexidine?',
    options: ['Apply it, let it dry fully, and keep it away from the drugs and needles', 'Pour chlorhexidine into a pot on the sterile trolley for easy re-use', 'Wipe it off with saline before puncture', 'Use 2% rather than 0.5% so less volume is needed'],
    answer: 0,
    explain: 'Chlorhexidine is neurotoxic. Keep it well away from the neuraxial drugs and equipment, never in pots on or near the same surface, and let it dry before you touch or puncture the skin. The Association of Anaesthetists prefers 0.5% chlorhexidine in alcohol.',
    refs: ['tq-campbell2014'],
    link: '#cx-wrong-route',
  },
  {
    topic: 'drugs',
    stem: 'Transient neurological symptoms after spinal anaesthesia are most strongly associated with which drug?',
    options: ['Bupivacaine', 'Prilocaine', 'Levobupivacaine', 'Lidocaine'],
    answer: 3,
    explain: 'In 1,863 patients, lidocaine carried a relative risk of 5.1 compared with bupivacaine. Lithotomy and day-case status increased the risk further.',
    refs: ['cx-freedman1998'],
    link: '#cx-tns',
  },
  {
    topic: 'drugs',
    stem: 'For a hyperbaric spinal, which factors matter most for how far the block spreads?',
    options: ['Patient weight and sex', 'Needle gauge and bevel direction', 'Baricity of the solution and the patient’s position', 'Speed of injection and barbotage'],
    answer: 2,
    explain: 'Baricity and position during and just after injection, with the dose, are the main controllable factors. Lumbosacral CSF volume explains much of the remaining variation but can’t be measured at the bedside. Speed of injection and barbotage have small, inconsistent effects.',
    refs: ['hocking2004'],
    link: '#tq-spread-h',
  },
  {
    topic: 'drugs',
    stem: 'According to the bupivacaine product label, what is the maximum dose in any 4-hour period?',
    options: ['1 mg/kg', '2 mg/kg', '3 mg/kg', '5 mg/kg'],
    answer: 1,
    explain: 'No more than 2 mg/kg in any 4 hours, with single doses up to 150 mg. A spinal dose is a small fraction of this, but add it to any peripheral block or infiltration given to the same patient.',
    refs: ['cx-marcain-smpc'],
    link: '#cx-last',
  },
  {
    topic: 'ultrasound',
    stem: 'Scanning in the paramedian sagittal oblique view, you find the flat bright sacrum. What is the first gap cranial to it?',
    options: ['L3–4', 'L4–5', 'L5–S1', 'S1–S2'],
    answer: 2,
    explain: 'The sacrum is a continuous bright line with no gaps. The first gap above it is L5–S1, the largest interlaminar space. Count up from there.',
    refs: ['us-nysora'],
    link: '#us-mark-level',
  },
  {
    topic: 'ultrasound',
    stem: 'Most of the evidence for ultrasound in neuraxial anaesthesia supports which use?',
    options: ['Real-time in-plane needle guidance', 'A pre-procedure scan to mark the level, midline and depth', 'Confirming CSF flow after puncture', 'Measuring block height after injection'],
    answer: 1,
    explain: 'The trials and meta-analyses mostly studied a pre-procedure scan: mark the skin, wipe off the gel and insert the needle as usual. Real-time guidance is technically demanding with limited data.',
    refs: ['perlas2016'],
    link: '#us-marking',
  },
  {
    topic: 'troubleshooting',
    stem: 'During injection the patient reports sharp pain shooting down one leg. What should you do?',
    options: ['Stop injecting, withdraw and redirect or re-site', 'Inject faster to finish quickly', 'Continue, as this is normal with hyperbaric solutions', 'Give IV fentanyl and continue'],
    answer: 0,
    explain: 'Pain on injection or persistent paraesthesia: stop, don’t inject, withdraw and redirect. Two-thirds of neurological deficits in a large French survey followed paraesthesia during puncture or pain on injection.',
    refs: ['ts-auroy1997'],
    link: '#ts-paraesthesia',
  },
  {
    topic: 'troubleshooting',
    stem: 'When is a repeat spinal most reasonable after a failed first attempt?',
    options: ['When there is no appreciable block at all after 15–20 min, and the cause has been dealt with', 'When the first block is patchy but rising slowly at 10 min', 'Whenever the surgeon is in a hurry', 'Always, using the same full dose'],
    answer: 0,
    explain: 'Repeat only after a complete failure, judged at 15–20 min. Repeating onto a slow or partial block risks an unpredictable high spinal and neurotoxic concentrations of local anaesthetic.',
    refs: ['fettes2009', 'ts-nysora-failed'],
    link: '#ts-failed',
  },
  {
    topic: 'troubleshooting',
    stem: 'A patient with a high spinal is hypotensive and bradycardic. Which position is recommended?',
    options: ['Head-down tilt', 'Sitting upright', 'Prone', 'Supine with the legs elevated, no head-down tilt'],
    answer: 3,
    explain: 'Elevate the legs to help venous return without tipping the head down, which could carry hyperbaric drug higher. Support the airway and circulation and call for help.',
    refs: ['ts-qrh2023'],
    link: '#ts-high-spinal',
  },
  {
    topic: 'anticoagulation',
    stem: 'A patient takes apixaban 5 mg twice daily for atrial fibrillation. What is the minimum interval from the last dose to a spinal?',
    options: ['12 h', '24 h', '36 h', '72 h'],
    answer: 3,
    explain: 'This is a high dose (AF stroke prevention). Both ESAIC/ESRA 2022 and ASRA 2025 give 72 h. 36 h applies only to low-dose prophylaxis after hip or knee replacement; ASRA counts the dose-reduced AF dose (also 2.5 mg twice daily) as high dose.',
    refs: ['esaic2022', 'asra2025'],
    link: '#tq-ac-full',
  },
  {
    topic: 'anticoagulation',
    stem: 'A patient had enoxaparin 40 mg once daily for thromboprophylaxis. How long after the last dose can a spinal be done, with normal renal function?',
    options: ['4 h', '12 h', '24 h', '72 h'],
    answer: 1,
    explain: 'Low-dose LMWH: at least 12 h. High (treatment) doses need 24 h, and ESAIC/ESRA extend the low-dose interval to 24 h if creatinine clearance is under 30 mL/min.',
    refs: ['esaic2022', 'asra2025'],
    link: '#tq-ac-full',
  },
  {
    topic: 'complications',
    stem: 'Under ICHD-3, which feature is required to diagnose post-dural puncture headache?',
    options: ['The headache is relieved within 15 min of lying flat', 'The headache starts within 5 days of a dural puncture', 'There is tinnitus or hearing loss', 'A blood patch relieves it'],
    answer: 1,
    explain: 'ICHD-3 requires a dural puncture and onset within 5 days, not better explained by another diagnosis. The postural feature is typical but no longer a required criterion.',
    refs: ['cx-ichd3', 'uppal2023'],
    link: '#cx-pdph',
  },
  {
    topic: 'complications',
    stem: 'What volume of blood does the 2023 multisociety consensus most often recommend for an epidural blood patch?',
    options: ['15–20 mL', '5 mL', '40 mL', 'As much as possible, up to 60 mL'],
    answer: 0,
    explain: 'Usually 15–20 mL, injected slowly, stopping if back pain, headache or radicular pressure becomes significant. More than 30 mL did not improve success.',
    refs: ['uppal2023'],
    link: '#cx-pdph',
  },
  {
    topic: 'complications',
    stem: 'Eight hours after a spinal the block had been wearing off, but now the patient’s legs are weaker and they have new back pain. What next?',
    options: ['Reassure: this is transient neurological symptoms', 'Wait a further 6 h for the block to wear off', 'Urgent MRI, call a senior anaesthetist and refer to neurosurgery', 'Give naloxone'],
    answer: 2,
    explain: 'A block that returns or worsens, with new back pain, is a vertebral canal haematoma or abscess until proven otherwise. ESAIC/ESRA advise urgent MRI and decompression, if indicated, within 6 h. TNS causes pain without weakness.',
    refs: ['esaic2022'],
    link: '#cx-haematoma',
  },
  {
    topic: 'complications',
    stem: 'How do NRFit (ISO 80369-6) connectors prevent wrong-route injection?',
    options: ['They are colour-coded yellow only', 'They contain a one-way valve', 'They will not connect to Luer syringes or lines', 'They only fit 25G needles'],
    answer: 2,
    explain: 'NRFit is a neuraxial-specific connector that will not mate with Luer, so an IV syringe or line can’t be attached to a spinal needle or epidural, and vice versa.',
    refs: ['iso80369-6'],
    link: '#cx-wrong-route',
  },
  {
    topic: 'complications',
    stem: 'Local anaesthetic systemic toxicity: what is the initial bolus of 20% lipid emulsion on the Association of Anaesthetists card?',
    options: ['0.5 mL/kg over 10 min', '5 mL/kg over 1 min', '100 mL regardless of weight', '1.5 mL/kg over 2–3 min'],
    answer: 3,
    explain: '1.5 mL/kg over 2–3 min, then an infusion of 15 mL/kg/h. Repeat the bolus at 5 and 10 min and double the infusion to 30 mL/kg/h if needed, to a maximum cumulative 12 mL/kg. Propofol is not a substitute.',
    refs: ['cx-qrh310'],
    link: '#cx-last',
  },
];

// SAQ / viva questions with model-answer points and marks.
export const SAQS = [
  {
    id: 'qz-saq-anatomy',
    q: 'Describe the structures a midline spinal needle passes through at L3–4, and explain why the level matters.',
    marks: 10,
    points: [
      ['Skin, subcutaneous fat, supraspinous ligament, interspinous ligament, ligamentum flavum, epidural space, dura and arachnoid, subarachnoid space (in order)', 3],
      ['Paramedian approach skips the supraspinous and interspinous ligaments', 1],
      ['Conus ends at a mean of the lower third of L1, range T12 to L3', 2, ['an-saifuddin1998']],
      ['Palpation identifies the space correctly only about 29% of the time, usually one or more levels higher than believed; Tuffier’s line is unreliable', 2, ['broadbent2000']],
      ['Conus injury has followed spinals placed higher than intended: insert at L3–4 or below, and consider ultrasound to confirm level', 2, ['reynolds2001']],
    ],
  },
  {
    id: 'qz-saq-spread',
    q: 'What factors affect the spread of intrathecal local anaesthetic? Which are most important?',
    marks: 10,
    points: [
      ['Drug: baricity (most important with position), dose (mass), volume at fixed concentration, temperature (plain bupivacaine is slightly hypobaric at 37 °C)', 3, ['hocking2004']],
      ['Patient: lumbosacral CSF volume (largest source of variation, not measurable clinically), age, raised intra-abdominal pressure, spinal curvature', 3, ['hocking2004']],
      ['Procedure: position during and after injection, level of injection, speed of injection and barbotage (small, inconsistent effects)', 2],
      ['Most predictable: a small volume of hyperbaric solution injected slowly, with the patient positioned deliberately afterwards', 2],
    ],
  },
  {
    id: 'qz-saq-failed',
    q: 'Twenty minutes after a spinal the patient can feel the surgeon’s pinch. Classify the causes of a failed spinal and outline your management.',
    marks: 10,
    points: [
      ['Define: anything from no block to inadequate height, density, duration or side', 1, ['fettes2009']],
      ['Causes (Fettes): failed lumbar puncture; pseudo-success; faulty injection; inadequate spread; failure of drug action; mismanagement of a successful block', 3, ['fettes2009']],
      ['Assess properly: autonomic and motor signs, test from the lowest dermatomes up with cold, pinprick and touch; allow 15–20 min before calling it failed', 2, ['ts-nysora-failed']],
      ['Manage by pattern: posture for a low hyperbaric block, unblocked side down if unilateral, supplementation or sedation, GA', 2],
      ['Repeat spinal only after complete failure: risk of high spinal and neurotoxicity; tell the surgeon and patient, document', 2, ['ts-nysora-failed']],
    ],
  },
  {
    id: 'qz-saq-pdph',
    q: 'A 35-year-old has a headache the day after a spinal for knee arthroscopy. How do you assess and manage it?',
    marks: 10,
    points: [
      ['ICHD-3: onset within 5 days of dural puncture; postural feature typical but not required; neck stiffness, hearing symptoms. Risk factors: younger age, female sex, previous PDPH, cutting or larger needles', 2, ['cx-ichd3', 'uppal2023']],
      ['Red flags and differentials: focal signs, seizures, fever, non-postural or changing headache; meningitis, subdural haematoma, venous sinus thrombosis', 2, ['uppal2023']],
      ['Conservative: paracetamol and NSAID; caffeine up to 900 mg/day in the first 24 h; drink normally; bed rest only for comfort', 2, ['uppal2023']],
      ['Epidural blood patch if activity limited: 15–20 mL at or below the puncture level, stop on back pain or pressure; complete relief 33–91%; counsel about repeat if within 48 h; follow up', 3, ['uppal2023']],
      ['Before a blood patch: exclude fever or sepsis, apply the antithrombotic timing rules, and consent for repeat dural puncture, backache and neurological complications; greater occipital nerve block (after a fine-gauge spinal) is a weaker alternative', 1, ['uppal2023']],
    ],
  },
  {
    id: 'qz-saq-apixaban',
    q: 'A patient on apixaban 5 mg twice daily for atrial fibrillation is listed for an elective knee replacement under spinal. How do you plan the anticoagulation?',
    marks: 10,
    points: [
      ['Classify as high dose (AF stroke prevention); check renal function and the time of the last dose', 2],
      ['Stop at least 72 h before the spinal (ESAIC/ESRA 2022; ASRA 2025); 36 h applies only to low-dose prophylaxis after hip or knee replacement; the dose-reduced AF dose of 2.5 mg twice daily still counts as high dose (ASRA 2025)', 3, ['esaic2022', 'asra2025']],
      ['If the interval is uncertain or short: a drug-specific level under 30 ng/mL; reversal agents (PCC, aPCC or andexanet) do not shorten the interval for an elective block', 2, ['esaic2022', 'asra2025']],
      ['Restart: ESAIC/ESRA only after any catheter is removed; ASRA 2025: first high-dose DOAC dose at least 24 h after the puncture; agree with surgeon and physician', 2, ['esaic2022', 'asra2025']],
      ['Document the plan, and do neurological checks after surgery', 1],
    ],
  },
  {
    id: 'qz-saq-high',
    q: 'Five minutes after a spinal, the patient says their hands feel weak and it is hard to breathe. Describe your recognition and management.',
    marks: 10,
    points: [
      ['Recognise the sequence (QRH 3-11): hypotension and bradycardia, difficulty breathing, arm weakness, impaired consciousness, then apnoea; it may progress slowly or fast', 2, ['ts-qrh2023']],
      ['Call for help; reassure (the patient may be aware); stop any further local anaesthetic', 1],
      ['Oxygen, jaw thrust, supraglottic airway or intubation with a reduced dose of induction agent; keep the patient asleep once intubated (risk of awareness)', 3, ['ts-qrh2023']],
      ['Circulation: IV fluid, legs elevated without head-down tilt, vasopressors and atropine, early adrenaline if severe; CPR if arrested', 3, ['ts-qrh2023']],
      ['Consider mimics (LAST, vasovagal, haemorrhage, embolism); debrief and document', 1],
    ],
  },
  {
    id: 'qz-saq-haematoma',
    q: 'What are the risk factors for, and features of, a vertebral canal haematoma after spinal anaesthesia? How do you manage a suspected case?',
    marks: 10,
    points: [
      ['Rare: e.g. 1 in 200,000 after obstetric epidural vs 1 in 3,600 in women having knee arthroplasty under neuraxial block', 2, ['cx-moen2004']],
      ['Risk factors: antithrombotic drugs and their combinations, traumatic puncture, catheter insertion and removal, older age, osteoporosis', 2, ['esaic2022', 'cx-moen2004']],
      ['Features: new back pain, leg weakness or numbness, bladder or bowel dysfunction, a block that lasts or spreads beyond the drug; motor signs often first', 2, ['esaic2022']],
      ['Urgent MRI, senior anaesthetist, neurosurgery; decompression within 6 h for recovery (ESAIC/ESRA); outcome better within 12 h in a surgical series', 3, ['esaic2022', 'cx-lawton1995']],
      ['Prevention: follow drug intervals; neuro checks for at least 24 h; document times', 1, ['esaic2022']],
    ],
  },
];
